[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "channels>=4.3.2",
    "daphne>=4.2.1",
    "django>=5.2.9",
    "djangorestframework>=3.16.1",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
]
